######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 30 13:38:59 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . sim-gui.app
INCLUDEPATH += .

# Input
HEADERS += dialog.h globals.h grid.h mainwindow.h ../life.h
FORMS += dialog.ui grid.ui mainwindow.ui
SOURCES += dialog.cpp grid.cpp mainwindow.cpp sim-gui.cpp
